blank_issues_enabled: true
contact_links:
  - name: 문서
    url: https://github.com/lledellebell/peek-carousel/blob/master/README.md
    about: README 문서를 확인해보세요
  - name: 토론
    url: https://github.com/lledellebell/peek-carousel/discussions
    about: 일반적인 토론은 Discussions를 이용해주세요
